"""Pure utility functions for hyperspectral image processing.

All functions are free of Qt imports so this module can be used
in tests and non-GUI contexts without a display.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

import numpy as np
import numpy.typing as npt


def find_rgb_bands(wavelengths: list[float]) -> Optional[tuple[int, int, int]]:
    """Return (r_idx, g_idx, b_idx) for the wavelength list, or None on failure.

    Assumes wavelengths are in ascending order.
    """
    R_WL = 682.5   # midpoint of 625–740 nm
    G_WL = 532.5   # midpoint of 495–570 nm
    B_WL = 472.5   # midpoint of 450–495 nm

    listlen = len(wavelengths)
    if listlen < 3:
        return None

    if wavelengths[0] > B_WL or wavelengths[-1] < R_WL:
        # Image doesn't span full RGB range — use evenly spaced indices.
        return (round(5 * listlen / 6), round(listlen / 2), round(listlen / 6))

    r_found = g_found = b_found = False
    r_diff = g_diff = b_diff = float("inf")
    r_idx = g_idx = b_idx = 0

    for i, wl in enumerate(wavelengths):
        if not r_found:
            d = abs(wl - R_WL)
            if d < r_diff:
                r_diff = d
            else:
                r_idx = i - 1
                r_found = True
        if not g_found:
            d = abs(wl - G_WL)
            if d < g_diff:
                g_diff = d
            else:
                g_idx = i - 1
                g_found = True
        if not b_found:
            d = abs(wl - B_WL)
            if d < b_diff:
                b_diff = d
            else:
                b_idx = i - 1
                b_found = True

    return (r_idx, g_idx, b_idx)


def find_red_nir_bands(wavelengths: list[float]) -> Optional[tuple[int, int]]:
    """Return (r_idx, nir_idx) or None if the image lacks the required range.

    Assumes wavelengths are in ascending order.
    """
    R_WL   = 682.5
    NIR_WL = 850.0

    listlen = len(wavelengths)
    if listlen < 2 or wavelengths[0] > R_WL or wavelengths[-1] < NIR_WL:
        return None

    r_found = nir_found = False
    r_diff = nir_diff = float("inf")
    r_idx = nir_idx = 0

    for i, wl in enumerate(wavelengths):
        if not r_found:
            d = abs(wl - R_WL)
            if d < r_diff:
                r_diff = d
            else:
                r_idx = i - 1
                r_found = True
        if not nir_found:
            d = abs(wl - NIR_WL)
            if d < nir_diff:
                nir_diff = d
            else:
                nir_idx = i - 1
                nir_found = True

    return (r_idx, nir_idx)


def read_psi_header(file_path: Path) -> dict[str, object]:
    """Parse a PSI-format header file into a metadata dictionary."""
    data: dict[str, object] = {}
    wavelengths: list[float] = []
    reading_wavelengths = False

    with file_path.open() as f:
        for line in f:
            parts = line.strip().split(" ")
            if "WAVELENGTHS" in parts:
                reading_wavelengths = True
                continue
            if "WAVELENGTHS_END" in parts:
                reading_wavelengths = False
                data["WAVELENGTHS"] = wavelengths
                continue
            if len(parts) == 2:
                key, value = parts
                data[key] = value
            elif reading_wavelengths and parts:
                wavelengths.append(float(parts[0]))

    return data


def create_envi_header(file_path: Path, meta: dict[str, object]) -> None:
    """Write an ENVI-standard header file from a PSI metadata dictionary."""
    with file_path.open("w") as f:
        f.write("ENVI\n")
        f.write("description = {Generated by Python}\n")
        f.write(f"bands = {{{meta['NBANDS']}}}\n")
        f.write("byte order = 0\n")
        f.write(f"data type = {{{meta['NBITS']}}}\n")
        f.write("file type = ENVI Standard\n")
        f.write("header offset = 0\n")
        f.write(f"interleave = {str(meta['LAYOUT']).lower()}\n")
        f.write(f"lines = {{{meta['NROWS']}}}\n")
        f.write(f"samples = {{{meta['NCOLS']}}}\n")
        f.write("wavelength units = nm\n")
        f.write("wavelength = {")
        f.write(",".join(map(str, meta["WAVELENGTHS"])))  # type: ignore[arg-type]
        f.write("}\n")


def numpy_to_qpixmap(image: npt.NDArray[np.uint8]) -> "QPixmap":
    """Convert a uint8 RGB numpy array (H, W, 3) to a QPixmap."""
    from PyQt6.QtGui import QImage, QPixmap

    height, width, channels = image.shape
    bytes_per_line = channels * width
    qimage = QImage(
        image.data, width, height, bytes_per_line, QImage.Format.Format_RGB888
    )
    return QPixmap.fromImage(qimage)
